version: 2
jobs:
  build:
    docker:
      - image: python:3.7.4-alpine3.9
    working_directory: /tmp
    shell: /bin/ash
    steps:
      - checkout
      - run:
        name: install aws-cli and set configure file
        command: |
          pip3 install awscli --upgrade --user;
          apk --update add groff;
          aws version;
#      - run:
#        name: deploy repositry to S3
#        command: |
#          aws s3 ls;

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branch:
              only:
                - master