version: 2
jobs:
  build:
    docker:
      - image: python:3.7.4-alpine3.9
    working_directory: /opt/cloudformation
    shell: /bin/ash
    steps:
      - checkout
      # install aws-cli and set configure file
      - run:
          command: |
            pip3 install awscli --upgrade --user;
            apk --update add groff;
            export PATH=$PATH:/root/.local/bin;
            aws --version;
            aws s3 sync /opt/cloudformation/ s3://yaizuuuu-cloudformation --delete \
              --exclude ".circleci*" \
              --exclude ".git*" \
              --exclude "*.md";

#workflows:
#  version: 2
#  build:
#    jobs:
#      - build:
#          filters:
#            branch:
#              only:
#                - master
