AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DomainName1:
    Description: Domain name 1
    Type: String
    ConstraintDescription: Domain name 1

Resources:
  # -------------------------
  # Certificate -> Domain
  # -------------------------
  SSLDomainName1Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName1
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}_${DomainName1}-domain'
      ValidationMethod: DNS
  # -------------------------
  # Certificate -> SubDomain
  # -------------------------
  SSLSubDomainName1Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName1}'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}_${DomainName1}-sub-domain'
      ValidationMethod: DNS
